# Generated by Django 4.2.10 on 2024-02-13 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelnewapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=250)),
                ('pimg', models.ImageField(upload_to='pics')),
                ('pdesc', models.TextField()),
            ],
        ),
    ]
